### ISSUE TITLE
Error when claim window opens

### ISSUE THREAD

**Issue by abhishek-botcraft** [erichlotto/yieldly-compounder#1]
The browser closes when the confirm claim window opens and then the script keeps retrying from the start. But always fails at that point.

**Comment by erichlotto** [comment]
Have you opted in on the contracts beforehand (importing a useable wallet instead of creating a new one)? In which claim does this error occurs? NLL or the Pool? I can only try again tomorrow when the rewards are distributed to participants

**Comment by abhishek-botcraft** [comment]
I am trying to run it on a raspberry pi and it happens there in the CLAIM NLL REWARDS step-

`YIELDLY AUTO COMPOUNDER v1.0.0
(node:5779) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at /home/pi/workspace/yieldly-compounder/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:217:63
    at new Promise (<anonymous>)
    at CDPSession.send (/home/pi/workspace/yieldly-compounder/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:216:16)
    at ExecutionContext._evaluateInternal (/home/pi/workspace/yieldly-compounder/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
    at ExecutionContext.evaluateHandle (/home/pi/workspace/yieldly-compounder/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:155:21)
    at WaitTask.rerun (/home/pi/workspace/yieldly-compounder/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:532:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5779) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5779) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I know that you have not tested this on a raspberry pi, but any help would be appreciated! TIA
